### PR TITLE
Fixed keylock error handling

### PR DESCRIPTION
**Pull request by TimurSungatullin**
Also made sending the request to a separate method. This will allow you to override this method. For example, to add a request retry in case of an error or custom error handling.

### CODE REVIEW

**Comment by TimurSungatullin** [comment]
I found the problem is that you are trying to get an error from method `raise_for_status`. But this method does not return an error, but raised does

**Comment by marcelo225** [comment]
Hi @TimurSungatullin !
I'm gonna merge your PR pretty soon. 
Have you ever run unit tests?

**Comment by marcelo225** [comment]
@TimurSungatullin appreciated for contributing to it

**Comment by TimurSungatullin** [comment]
Hi @marcelo225 
Thank you!
Yes, I ran existing tests and wrote my own, everything went well

**Pull request merged**
